openapi: 3.0.0
info:
  title: Vast.ai Instance Creation API
  description: API endpoint for creating new instances by accepting provider offers
  version: 1.0.0
servers:
- url: https://console.vast.ai
  description: Production server
paths:
  /api/v0/asks/{id}/:
    put:
      summary: create instance
      description: 'Creates a new instance by accepting an "ask" contract from a provider.
        This is the main endpoint for launching new instances on Vast.ai.

        CLI Usage: vast create instance <offer_id> [options]'
      security:
      - ApiKeyAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: ID of the offer to accept
      - name: api_key
        in: query
        required: true
        schema:
          type: string
        description: API key for authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                template_id:
                  type: integer
                  description: Optional template ID to use for instance configuration
                  example: 89
                template_hash_id:
                  type: string
                  description: Optional template hash ID to use for instance configuration
                  example: abc123def456
                image:
                  type: string
                  description: Docker image to use for the instance
                  example: tensorflow/tensorflow:latest-gpu
                  maxLength: 1024
                disk:
                  type: number
                  description: Storage space in GB
                  minimum: 8.0
                  default: 10.0
                  example: 32.0
                env:
                  type: object
                  description: Environment variables and port mappings
                  example:
                    JUPYTER_TOKEN: abc123
                    PORTAL_CONFIG: '{"ports": [8080, 8081]}'
                  maxLength: 256
                runtype:
                  type: string
                  description: Instance run type
                  enum:
                  - ssh
                  - jupyter
                  - args
                  - ssh_proxy
                  - ssh_direct
                  - jupyter_proxy
                  - jupyter_direct
                  example: jupyter
                onstart:
                  type: string
                  description: Commands to run when instance starts
                  maxLength: 4096
                  example: pip install -r requirements.txt
                label:
                  type: string
                  description: User-defined label for the instance
                  maxLength: 256
                  example: training-job-1
                image_login:
                  type: string
                  description: Docker registry credentials if needed
                  example: -u username -p password docker.io
                price:
                  type: number
                  description: Bid price per hour for interruptible instances
                  minimum: 0.001
                  maximum: 128.0
                  example: 0.4
                target_state:
                  type: string
                  description: Desired initial state of the instance
                  enum:
                  - running
                  - stopped
                  default: running
                  example: running
                cancel_unavail:
                  type: boolean
                  description: Whether to cancel if instance cannot start immediately. Defaults to false for interruptibles, true for on-demand with target_state='running'
                  example: true
                vm:
                  type: boolean
                  description: Whether this is a VM instance
                  default: false
                client_id:
                  type: string
                  description: Client identifier (usually "me")
                  example: me
                apikey_id:
                  type: string
                  description: Optional API key identifier for audit logging
                args:
                  type: array
                  items:
                    type: string
                  description: Arguments to pass to the container entrypoint
                  example: ["-c", "echo hello; sleep infinity;"]
                entrypoint:
                  type: string
                  description: Override entrypoint for args launch instance
                  example: bash
                use_ssh:
                  type: boolean
                  description: Launch as an SSH instance type (deprecated, use runtype instead)
                python_utf8:
                  type: boolean
                  description: Set python's locale to C.UTF-8
                lang_utf8:
                  type: boolean
                  description: Install and generate locales before instance launch, set locale to C.UTF-8
                use_jupyter_lab:
                  type: boolean
                  description: Launch instance with jupyter lab instead of notebook
                jupyter_dir:
                  type: string
                  description: Directory in instance to use to launch jupyter
                force:
                  type: boolean
                  description: Skip sanity checks when creating from an existing instance
                user:
                  type: string
                  description: User to use with docker create (breaks some images, use with caution)
                volume_info:
                  type: object
                  description: Volume creation/linking information
                  properties:
                    create_new:
                      type: boolean
                      description: Whether to create a new volume
                    volume_id:
                      type: integer
                      description: ID of existing volume to link or volume offer ID for new volume
                    size:
                      type: integer
                      description: Size of the volume in GB (for new volumes)
                    mount_path:
                      type: string
                      description: Mount path for the volume inside the container
                    name:
                      type: string
                      description: Label for the new volume
      responses:
        '200':
          description: Instance created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  new_contract:
                    type: integer
                    description: ID of the newly created instance contract
                    example: 1234568
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    enum:
                    - invalid_args
                    - invalid_price
                    - no_ssh_key_for_vm
                  msg:
                    type: string
                    example: "error 400/3467: Invalid args: 'id' is required and must be a valid offer ID"
                  ask_id:
                    type: integer
                    example: 1234567
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: invalid_args
                  msg:
                    type: string
                    example: "error 403/3586: Offer 1234567 is not your own. Hosts can only rent their own machines."
                  ask_id:
                    type: integer
                    example: 1234567
        '404':
          description: Offer not found or not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: invalid_args
                  msg:
                    type: string
                    example: "error 404/3603: no_such_ask Instance type by id 1234567 is not available."
                  ask_id:
                    type: integer
                    example: 1234567
        '410':
          description: Offer no longer available (when cancel_unavail is true and instance cannot start)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: no_such_ask
                  msg:
                    type: string
                    example: "error 410/3907: no_such_ask Instance type 1234567 is no longer available."
                  ask_id:
                    type: integer
                    example: 1234567
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: API requests too frequent endpoint threshold=4.5
      tags:
      - Instances
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: api_key
      description: API key must be provided as a query parameter
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        msg:
          type: string
x-rate-limit:
  threshold: 4.5
  penalty: 12
  per: request
  description: Maximum request frequency per IP address for this endpoint
x-input-validation:
  image:
    max_length: 1024
    description: Docker image name
  args:
    max_length: 4096
    description: Combined length of args, args_str and onstart
  label:
    max_length: 256
    description: Instance label
  env:
    max_length: 256
    max_total_length: 32768
    description: Environment variables
  price:
    min: 0.001
    max: 128.0
    description: Min/max bid price for interruptible instances
  disk:
    min: 8.0
    default: 10.0
    description: Minimum storage space in GB
x-cli-commands:
- name: create instance
  description: Create a new instance from an offer
  endpoint: /api/v0/asks/{id}/
  method: PUT
  examples:
  - vast create instance 1234567 --image tensorflow/tensorflow:latest-gpu --disk 32
  - vast create instance 1234567 --template abc123def456
  - vast create instance 1234567 --price 0.4 --disk 100 --env JUPYTER_TOKEN=abc123