openapi: 3.0.0
info:
  title: Vast.ai Search Offers API
  description: 'API endpoint to search and retrieve filtered GPU machine offers'
  version: 1.0.0
servers:
- url: https://console.vast.ai
  description: Production server
paths:
  /api/v0/bundles/:
    post:
      summary: search offers
      description: |
        Search for available GPU machine offers with advanced filtering and sorting.

        Each filter parameter (such as `verified`, `gpu_name`, `num_gpus`, etc.) should be an object specifying the operator and value you want to match.

        **Supported filter operators:**

        | Operator | Meaning                | Example                        |
        |:---------|:-----------------------|:-------------------------------|
        | `eq`     | Equal to               | `{ "eq": true }`               |
        | `neq`    | Not equal to           | `{ "neq": false }`             |
        | `gt`     | Greater than           | `{ "gt": 0.99 }`               |
        | `lt`     | Less than              | `{ "lt": 10000 }`              |
        | `gte`    | Greater than or equal  | `{ "gte": 4 }`                 |
        | `lte`    | Less than or equal     | `{ "lte": 8 }`                 |
        | `in`     | Value is in a list     | `{ "in": ["RTX_3090", "RTX_4090"] }` |
        | `nin`    | Value is not in a list | `{ "nin": ["TW", "SE"] }`      |

        Default filters applied unless --no-default:
        - verified: true
        - external: false  
        - rentable: true
        - rented: false

        CLI Usage: `vastai search offers 'reliability > 0.99 num_gpus>=4' --order=dph_total`
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                verified:
                  type: object
                  description: Machine verification status
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: true
                rentable:
                  type: object
                  description: Whether machine is rentable
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: true
                external:
                  type: object
                  description: External machine status
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: false
                rented:
                  type: object
                  description: Current rental status
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: false
                gpu_name:
                  type: object
                  description: GPU model name
                  properties:
                    eq:
                      type: string
                reliability:
                  type: object
                  description: Machine reliability score (Any decimal number between 0-1)
                num_gpus:
                  type: object
                  description: Number of GPUs
                cuda_max_good:
                  type: object
                  description: Maximum CUDA version
                gpu_ram:
                  type: object
                  description: GPU memory in MB
                dlperf_per_dphtotal:
                  type: object
                  description: DLPerf per dollar per hour
                inet_down:
                  type: object
                  description: Download bandwidth (MB/s)
                inet_up:
                  type: object
                  description: Upload bandwidth (MB/s)
                direct_port_count:
                  type: object
                  description: Number of direct ports
                geolocation:
                  type: object
                  description: Machine location (two letter country code)
                bw_nvlink:
                  type: object
                  description: Bandwidth NVLink
                compute_cap:
                  type: object
                  description: CUDA compute capability*100 (650 for 6.5, 700 for
                    7.0)
                cpu_arch:
                  type: object
                  description: Host machine CPU architecture (e.g. amd64, arm64)
                cpu_cores:
                  type: object
                  description: Number of virtual CPUs
                cpu_ghz:
                  type: object
                  description: CPU clock speed in GHz
                datacenter:
                  type: object
                  description: Show only datacenter offers
                disk_bw:
                  type: object
                  description: Disk read bandwidth in MB/s
                dlperf:
                  type: object
                  description: Deep Learning performance score
                dlperf_usd:
                  type: object
                  description: DLPerf per dollar
                driver_version:
                  type: object
                  description: NVIDIA driver version as 3 digit string
                duration:
                  type: object
                  description: Maximum rental duration in seconds
                flops_usd:
                  type: object
                  description: TFLOPs per dollar
                gpu_arch:
                  type: object
                  description: Host machine GPU architecture (e.g. nvidia, amd)
                gpu_max_power:
                  type: object
                  description: GPU power limit in watts
                gpu_max_temp:
                  type: object
                  description: GPU temperature limit in Celsius
                gpu_mem_bw:
                  type: object
                  description: GPU memory bandwidth in GB/s
                gpu_total_ram:
                  type: object
                  description: Total GPU RAM across all GPUs in GB
                gpu_frac:
                  type: object
                  description: Ratio of GPUs in offer to GPUs in system
                gpu_display_active:
                  type: object
                  description: Whether GPU has a display attached
                has_avx:
                  type: object
                  description: CPU supports AVX instruction set
                pci_gen:
                  type: object
                  description: PCIe generation
                storage_cost:
                  type: object
                  description: Storage cost in $/GB/month
                static_ip:
                  type: object
                  description: Whether the IP address is static/stable
                total_flops:
                  type: object
                  description: Total TFLOPs from all GPUs
                ubuntu_version:
                  type: object
                  description: Host machine Ubuntu OS version
                vms_enabled:
                  type: object
                  description: Whether the machine is a VM instance
                machine_id:
                  type: object
                  description: Filter by specific host machine ID
                order:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                  description: Sort fields and directions
                type:
                  type: string
                  enum:
                  - on-demand
                  - bid
                  - reserved
                  description: Contract type filter
                limit:
                  type: integer
                  description: Max results to return
                disable_bundling:
                  type: boolean
                  description: Disable offer bundling
                allocated_storage:
                  type: number
                  description: Required storage in GB
      responses:
        '200':
          description: Successful search response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  offers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Unique offer ID
                        cuda_max_good:
                          type: number
                          description: Maximum CUDA version
                        num_gpus:
                          type: integer
                          description: Number of GPUs
                        gpu_name:
                          type: string
                          description: GPU model name
                        pcie_bw:
                          type: number
                          description: PCIe bandwidth
                        cpu_cores_effective:
                          type: number
                          description: Available CPU cores
                        cpu_ram:
                          type: number
                          description: RAM in GB
                        disk_space:
                          type: number
                          description: Storage space in GB
                        dph_total:
                          type: number
                          description: Total dollars per hour
                        dlperf:
                          type: number
                          description: Deep learning performance score
                        dlperf_per_dphtotal:
                          type: number
                          description: DLPerf per dollar per hour
                        inet_up:
                          type: number
                          description: Upload bandwidth (MB/s)
                        inet_down:
                          type: number
                          description: Download bandwidth (MB/s)
                        reliability:
                          type: number
                          description: Score  (0-1)
                        verified:
                          type: boolean
                          description: Verification status
                        rentable:
                          type: boolean
                          description: Rental availability
                        rented:
                          type: boolean
                          description: Current rental status
                        machine_id:
                          type: integer
                          description: Host machine ID
                        geolocation:
                          type: string
                          description: Geographic location
                        direct_port_count:
                          type: integer
                          description: Number of direct ports
                        max_bid:
                          type: number
                          description: Maximum bid allowed
                        min_bid:
                          type: number
                          description: Minimum bid required
                        bw_nvlink:
                          type: number
                          description: NVLink bandwidth
                        compute_cap:
                          type: integer
                          description: CUDA compute capability
                        cpu_arch:
                          type: string
                          description: CPU architecture
                        gpu_arch:
                          type: string
                          description: GPU architecture
                        driver_version:
                          type: string
                          description: NVIDIA driver version
                        ubuntu_version:
                          type: string
                          description: Ubuntu OS version
        '400':
          description: Bad request - invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
      - Search
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: API key must be provided in the Authorization header
  schemas:
    Error:
      type: object
      required:
      - success
      - error
      - msg
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error code
          example: invalid_query
        msg:
          type: string
          description: Human readable error message
          example: Invalid query parameters
x-tags:
- name: Search
  description: Endpoints for searching offers
x-rate-limit:
  requests: 10
  per: minute
  description: Rate limit per IP address