openapi: 3.0.0
info:
  title: Vast.ai Search Offers API
  description: 'API endpoint to search and retrieve filtered GPU machine offers'
  version: 1.0.0
servers:
- url: https://console.vast.ai
  description: Production server
paths:
  /api/v0/bundles/:
    post:
      summary: search offers
      description: |
        Search for available GPU machine offers with advanced filtering and sorting.

        Each filter parameter (such as `verified`, `gpu_name`, `num_gpus`, etc.) should be an object specifying the operator and value you want to match.

        **Supported filter operators:**

        | Operator | Meaning                | Example                        |
        |:---------|:-----------------------|:-------------------------------|
        | `eq`     | Equal to               | `{ "eq": true }`               |
        | `neq`    | Not equal to           | `{ "neq": false }`             |
        | `gt`     | Greater than           | `{ "gt": 0.99 }`               |
        | `lt`     | Less than              | `{ "lt": 10000 }`              |
        | `gte`    | Greater than or equal  | `{ "gte": 4 }`                 |
        | `lte`    | Less than or equal     | `{ "lte": 8 }`                 |
        | `in`     | Value is in a list     | `{ "in": ["RTX_3090", "RTX_4090"] }` |
        | `nin`    | Value is not in a list | `{ "nin": ["TW", "SE"] }`      |

        Default filters applied unless --no-default:
        - verified: true
        - rentable: true
        - rented: false

        CLI Usage: `vastai search offers 'reliability > 0.99 num_gpus>=4' --order=dph_total`
      security:
      - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: integer
                  description: Max results to return
                verified:
                  type: object
                  description: Machine verification status
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: true
                rentable:
                  type: object
                  description: Whether machine is rentable
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: true
                rented:
                  type: object
                  description: Current rental status
                  properties:
                    eq:
                      type: boolean
                  default:
                    eq: false
                type:
                  type: string
                  enum:
                  - on-demand
                  - bid
                  - reserved
                gpu_name:
                  type: object
                  description: GPU model name
                reliability:
                  type: object
                  description: Machine reliability score (Any decimal number between 0-1)
                num_gpus:
                  type: object
                  description: Number of GPUs
                cuda_max_good:
                  type: object
                  description: Maximum CUDA version
                gpu_ram:
                  type: object
                  description: GPU memory in MB
                dlperf_per_dphtotal:
                  type: object
                  description: DLPerf per dollar per hour
                inet_down:
                  type: object
                  description: Download bandwidth (MB/s)
                inet_up:
                  type: object
                  description: Upload bandwidth (MB/s)
                direct_port_count:
                  type: object
                  description: Number of direct ports
                geolocation:
                  type: object
                  description: Machine location (two letter country code)
                compute_cap:
                  type: object
                  description: CUDA compute capability*100 (650 for 6.5, 700 for
                    7.0)
                cpu_arch:
                  type: object
                  description: Host machine CPU architecture (e.g. amd64, arm64)
                cpu_cores:
                  type: object
                  description: Number of virtual CPUs
                cpu_ghz:
                  type: object
                  description: CPU clock speed in GHz
                cpu_ram:
                  type: object
                  description: RAM in MB
                datacenter:
                  type: object
                  description: Show only datacenter offers
                  properties:
                    eq:
                      type: boolean
                disk_bw:
                  type: object
                  description: Disk read bandwidth in MB/s
                bw_nvlink:
                  type: object
                  description: NVLink bandwidth
                dlperf:
                  type: object
                  description: Deep Learning performance score
                driver_version:
                  type: object
                  description: NVIDIA driver version in the format "XXX.XX.XX
                duration:
                  type: object
                  description: Maximum rental duration in seconds
                gpu_arch:
                  type: object
                  description: Host machine GPU architecture (e.g. nvidia, amd)
                gpu_max_power:
                  type: object
                  description: GPU power limit in watts
                gpu_max_temp:
                  type: object
                  description: GPU temperature limit in Celsius
                gpu_mem_bw:
                  type: object
                  description: GPU memory bandwidth in GB/s
                gpu_total_ram:
                  type: object
                  description: Total GPU RAM across all GPUs in MB
                gpu_frac:
                  type: object
                  description: Ratio of GPUs in offer to GPUs in system
                pci_gen:
                  type: object
                  description: PCIe generation
                storage_cost:
                  type: object
                  description: Storage cost in $/GB/month
                static_ip:
                  type: object
                  description: Whether the IP address is static/stable
                total_flops:
                  type: object
                  description: Total TFLOPs from all GPUs
                os_version:
                  type: object
                  description: Host machine Ubuntu OS version
                machine_id:
                  type: object
                  description: Filter by specific host machine ID
                order:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                  description: Sort fields and directions
                disable_bundling:
                  type: boolean
                  description: Disable offer bundling
                allocated_storage:
                  type: number
                  description: Required storage in GB
      responses:
        '200':
          description: Successful search response
          content:
            application/json:
              example:
                offers:
                  id: 12345678
                  ask_contract_id: 12345678
                  bundle_id: 987654321
                  bundled_results: null
                  bw_nvlink: 0
                  compute_cap: 900
                  cpu_arch: "amd64"
                  cpu_cores: 64
                  cpu_cores_effective: 32
                  cpu_ghz: 2.99
                  cpu_name: "QuantumX 128-Core Processor"
                  cpu_ram: 65536
                  credit_discount_max: 0.15
                  cuda_max_good: 11.2
                  direct_port_count: 42
                  disk_bw: 1234.5
                  disk_name: "HYPERDISK 8TB"
                  disk_space: 2048.5
                  dlperf: 222.22
                  dlperf_per_dphtotal: 333.33
                  dph_base: 0.123456
                  dph_total: 0.234567
                  driver_version: "999.99.99"
                  driver_vers: 999999999
                  duration: 1234567.89
                  end_date: 1893456000
                  external: null
                  flops_per_dphtotal: 444.44
                  geolocation: "Atlantis, AT"
                  geolocode: 42424242
                  gpu_arch: "nvidia"
                  gpu_display_active: false
                  gpu_frac: 0.75
                  gpu_ids: [1111, 2222]
                  gpu_lanes: 16
                  gpu_mem_bw: 888.8
                  gpu_name: "Imaginary RTX 9999"
                  gpu_ram: 24576
                  gpu_total_ram: 49152
                  gpu_max_power: 450
                  gpu_max_temp: 42
                  has_avx: 1
                  host_id: 55555
                  hosting_type: 0
                  hostname: null
                  inet_down: 9876.5
                  inet_down_cost: 0.00123
                  inet_up: 8765.4
                  inet_up_cost: 0.00456
                  is_bid: false
                  logo: "/static/logos/fake_logo.png"
                  machine_id: 88888
                  min_bid: 0.111111
                  mobo_name: "FANTASY-MOBO-2025"
                  num_gpus: 4
                  os_version: "42.42"
                  pci_gen: 6
                  pcie_bw: 99.9
                  public_ipaddr: "203.0.113.42"
                  reliability: 0.9999
                  reliability_mult: 0.8888
                  rentable: true
                  rented: false
                  score: 1234.5678
                  start_date: 1893450000.5
                  static_ip: true
                  storage_cost: 0.987654
                  storage_total_cost: 0.123456
                  total_flops: 999.99
                  verification: "verified"
                  vericode: 1
                  vram_costperhour: 0.009876
                  webpage: null
                  vms_enabled: false
                  expected_reliability: 0.5
                  is_vm_deverified: false
                  resource_type: "gpu"
                  cluster_id: null
                  avail_vol_ask_id: 333333
                  avail_vol_dph: 0.000321
                  avail_vol_size: 4096
                  nw_disk_min_bw: null
                  nw_disk_max_bw: null
                  nw_disk_avg_bw: null
                  rn: 1
                  dph_total_adj: 0.345678
                  reliability2: 0.9999
                  discount_rate: 0.05
                  discounted_hourly: 0.01
                  discounted_dph_total: 0.224567
                  search:
                    gpuCostPerHour: 0.123456
                    diskHour: 0.123456
                    totalHour: 0.234567
                    discountTotalHour: 0.01
                    discountedTotalPerHour: 0.224567
                  instance:
                    gpuCostPerHour: 0.01
                    diskHour: 0.02
                    totalHour: 0.03
                    discountTotalHour: 0.001
                    discountedTotalPerHour: 0.029
                  time_remaining: ""
                  time_remaining_isbid: ""
                  internet_up_cost_per_tb: 1.23
                  internet_down_cost_per_tb: 4.56
        '400':
          description: Bad request - invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
      - Search
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: API key must be provided in the Authorization header
  schemas:
    Error:
      type: object
      required:
      - success
      - error
      - msg
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error code
          example: invalid_query
        msg:
          type: string
          description: Human readable error message
          example: Invalid query parameters
x-tags:
- name: Search
  description: Endpoints for searching offers
x-rate-limit:
  requests: 10
  per: minute
  description: Rate limit per IP address