openapi: 3.0.0
info:
  title: Vast.ai API
  version: 1.0.0
paths:
  /api/v0/team/roles/{id}/:
    put:
      summary: update team role
      description: |
        Update an existing team role with new name and permissions.

        CLI Usage: `vastai update team-role <id> --name <new_name> --permissions <new_permissions_json>`
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the role to update.
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: New name for the role.
                permissions:
                  type: object
                  description: JSON encoded permissions for the role.
              required:
              - name
              - permissions
      responses:
        '200':
          description: Successfully updated team role.
          content:
            application/json:
              schema:
                type: string
                example: Successfully Updated Team Role For <role_name>
      security:
      - apiKeyAuth: []
      tags:
      - Team
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
x-cli-commands:
- name: update team-role
  description: Update an existing team role
  endpoint: /api/v0/team/roles/{id}/
  method: put
  example: "vastai update team-role 1234 --name \"new_role_name\" --permissions '{\"api\": {\"user_read\": {}, \"instance_write\": {}}}'"