on:
  push:
    paths:
      - 'openapi/yaml/*.yaml'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vast-cli
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Run combine script
        run: python openapi/combine_api_yamls.py

      - name: Convert YAML to JSON
        run: |
          # example: using yq
          pip install yq
          yq . openapi/yaml/combined_api.yaml > openapi.json

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          repository: vast-ai/docs
          token: ${{ secrets.UPDATE_API_DOCS_TOKEN }}
          path: docs-repo

      - name: Copy openapi.json to docs
        run: cp openapi.json docs-repo/api-reference/openapi.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.UPDATE_API_DOCS_TOKEN }}
          path: docs-repo
          commit-message: 'Update openapi.json from vast-cli'
          title: 'Automated update of openapi.json'
          body: 'This PR updates the openapi.json based on latest changes in vast-cli.'